parameters:
    tmdb.api_key: '%env(TMDB_API_KEY)%'

services:
    # Configuration par défaut pour les services
    _defaults:
        autowire: true
        autoconfigure: true

    # Charge automatiquement les classes dans src/
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Configuration explicite pour TmdbApiService
    App\Service\TmdbApiService:
        arguments:
            $apiKey: '%tmdb.api_key%'
